In [1]:
from pathlib import Path
import sqlite3 as sql

In [2]:
conn=sql.connect('hims.db')

In [3]:
conn.row_factory = sql.Row

In [5]:
cur = conn.cursor()

In [14]:
cur.execute("select fullname from patients ;")

In [15]:
[list(i) for i in cur.fetchall()]

[['kunal'],
 ['raam'],
 ['Hari Prasad'],
 ['Priya Kumar'],
 ['Arjun Dutta'],
 ['Anjali Rana'],
 ['Divya Patel'],
 ['Rajat Verma'],
 ['Arjun Bansal'],
 ['Divya Rana'],
 ['Rakesh Mehta'],
 ['Rakesh Mukherjee'],
 ['Rahul Roy'],
 ['Tarun Ghosh'],
 ['Manish Prasad'],
 ['Manish Tiwari'],
 ['Muskan Reddy'],
 ['Akash Kumar'],
 ['Swati Iyer'],
 ['Swati Desai'],
 ['Shubham Kapoor'],
 ['Kabir Saxena'],
 ['Rohan Banerjee'],
 ['Abhishek Patel'],
 ['Sakshi Prasad'],
 ['Rahul Nair'],
 ['Swati Yadav'],
 ['Rekha Ghosh'],
 ['Rahul Tiwari'],
 ['Varun Rana'],
 ['Mansi Mishra'],
 ['Piyush Sinha'],
 ['Kavya Patel'],
 ['Bhavna Rao'],
 ['Sonia Mishra'],
 ['Divya Desai'],
 ['Radhika Nair'],
 ['Abhishek Menon'],
 ['Rahul Prasad'],
 ['Aarav Kapoor'],
 ['Divya Verma'],
 ['Varun Rana'],
 ['Vivek Bansal'],
 ['Rajesh Desai'],
 ['Sameer Kumar'],
 ['Dhruv Chopra'],
 ['Juhi Iyer'],
 ['Bhavna Prasad'],
 ['Nandini Bansal'],
 ['Abhishek Sethi'],
 ['Harsh Agarwal'],
 ['Muskan Arora'],
 ['Tanvi Saxena'],
 ['Dev Rana'],
 ['Aditya Patel'],
 ['Preeti Rao'],
 ['Bhavna Jain'],
 ['Riya Nair'],
 ['Varun Prasad'],
 ['Juhi Ghosh'],
 ['Shubham Sharma'],
 ['Sonia Reddy'],
 ['Riya Khanna'],
 ['Amit Rao'],
 ['Amit Banerjee'],
 ['Manish Das'],
 ['Sunita Mehta'],
 ['Shreya Ghosh'],
 ['Dhruv Pandey'],
 ['Rohan Reddy'],
 ['Dev Yadav'],
 ['Rajesh Jain'],
 ['Madan Patel'],
 ['Meera Menon'],
 ['Aarav Verma'],
 ['Ritvik Reddy'],
 ['Rajesh Kumar'],
 ['Pranav Desai'],
 ['Rohan Arora'],
 ['Riya Arora'],
 ['Nandini Prasad'],
 ['Payal Shah'],
 ['Amit Bansal'],
 ['Rahul Bansal'],
 ['Anjali Mukherjee'],
 ['Dhruv Kapoor'],
 ['Ayush Jain'],
 ['Nisha Menon'],
 ['Komal Arora'],
 ['Vivek Patel'],
 ['Isha Prasad'],
 ['Gaurav Sharma'],
 ['Tanya Pandey'],
 ['Dhruv Joshi'],
 ['Harsh Nair'],
 ['Ishaan Sharma'],
 ['Rajesh Yadav'],
 ['Ayush Menon'],
 ['Sameer Mukherjee'],
 ['Juhi Prasad'],
 ['Aditi Das'],
 ['Shubham Ghosh'],
 ['Anil Srivastava'],
 ['Palak Kapoor'],
 ['Isha Patel'],
 ['Rekha Patel'],
 ['Kriti Banerjee'],
 ['Anjali Khanna'],
 ['Madan Saxena'],
 ['Arjun Rana'],
 ['Sakshi Nair'],
 ['Dev Desai'],
 ['Rohan Bansal'],
 ['Vikram Mukherjee'],
 ['Preeti Agarwal'],
 ['Priya Sinha'],
 ['Kavya Rao'],
 ['Madan Prasad'],
 ['Aditya Bansal'],
 ['Nisha Patel'],
 ['Shubham Rana'],
 ['Swati Menon'],
 ['Juhi Khanna'],
 ['Anjali Roy'],
 ['Kiran Iyer'],
 ['Preeti Sinha'],
 ['Aanya Sinha'],
 ['Dev Khanna'],
 ['Riya Nair'],
 ['Kriti Reddy'],
 ['Siddharth Pandey'],
 ['Sakshi Singh'],
 ['Isha Menon'],
 ['Deepak Chopra'],
 ['Ritvik Singh'],
 ['Ravi Nair'],
 ['Tarun Sethi'],
 ['Ritvik Roy'],
 ['Aditya Gupta'],
 ['Palak Roy'],
 ['Arjun Kumar'],
 ['Ishaan Bansal'],
 ['Pooja Das'],
 ['Yash Singh'],
 ['Aman Verma'],
 ['Sunita Khanna'],
 ['Arjun Sethi'],
 ['Saurabh Chopra'],
 ['Bhavna Banerjee'],
 ['Mansi Gupta'],
 ['Isha Iyer'],
 ['Vivek Reddy'],
 ['Siddharth Ghosh'],
 ['Piyush Kapoor'],
 ['Rajesh Dutta'],
 ['Deepak Das'],
 ['Rakesh Kumar'],
 ['Radhika Gupta'],
 ['Ananya Das'],
 ['Amit Joshi'],
 ['Swati Reddy'],
 ['Meera Joshi'],
 ['Dev Verma'],
 ['Sakshi Dutta'],
 ['Vivaan Malhotra'],
 ['Riya Agarwal'],
 ['Yash Desai'],
 ['Piyush Rana'],
 ['Rajesh Tiwari'],
 ['Anjali Pandey'],
 ['Priya Arora'],
 ['Vivek Arora'],
 ['Varun Mishra'],
 ['Mohit Ghosh'],
 ['Gaurav Malhotra'],
 ['Isha Kumar'],
 ['Mohit Rao'],
 ['Vivaan Dutta'],
 ['Mansi Patel'],
 ['Kavya Rana'],
 ['Muskan Malhotra'],
 ['Tarun Desai'],
 ['Ravi Das'],
 ['Manish Kapoor'],
 ['Neeraj Roy'],
 ['Nisha Banerjee'],
 ['Varun Verma'],
 ['Aditya Gupta'],
 ['Mohit Tiwari'],
 ['Rajat Kumar'],
 ['Sneha Shah'],
 ['Karan Mishra'],
 ['Akash Patel'],
 ['Ayush Nair'],
 ['Sunita Nair'],
 ['Aarav Dutta'],
 ['Ananya Menon'],
 ['Amit Gupta'],
 ['Payal Jain'],
 ['Aditya Arora'],
 ['Arjun Rao'],
 ['Simran Verma'],
 ['Rajat Rao'],
 ['Deepa Tiwari'],
 ['Karan Kapoor'],
 ['Rekha Srivastava'],
 ['Swati Rana'],
 ['Gaurav Kapoor'],
 ['Kriti Kumar'],
 ['Aanya Mishra'],
 ['Anjali Nair'],
 ['Aditi Srivastava'],
 ['Madan Ghosh'],
 ['Shruti Desai'],
 ['Ayush Mishra'],
 ['Simran Singh'],
 ['Mansi Saxena'],
 ['Mohit Mishra'],
 ['Swati Khanna'],
 ['Sakshi Malhotra'],
 ['Isha Patel'],
 ['Muskan Saxena'],
 ['Simran Kumar'],
 ['Anil Joshi'],
 ['Aarav Das'],
 ['Mansi Roy'],
 ['Rohan Roy'],
 ['Aditi Mehta'],
 ['Dhruv Jain'],
 ['Ritvik Pandey'],
 ['Naveen Prasad'],
 ['Pranav Ghosh'],
 ['Nikhil Mukherjee'],
 ['Vivek Patel'],
 ['Yash Rao'],
 ['Riya Dutta'],
 ['Ayush Prasad'],
 ['Ayush Roy'],
 ['Tarun Mukherjee'],
 ['Kabir Sinha'],
 ['Kiran Joshi'],
 ['Muskan Srivastava'],
 ['Madan Joshi'],
 ['Deepa Rana'],
 ['Akash Sharma'],
 ['Mohit Sinha'],
 ['Radhika Ghosh'],
 ['Dev Mishra'],
 ['Gaurav Singh'],
 ['Isha Patel'],
 ['Rohan Shah'],
 ['Amit Prasad'],
 ['Tanya Iyer'],
 ['Tanvi Khanna'],
 ['Rakesh Prasad'],
 ['Palak Agarwal'],
 ['Simran Roy'],
 ['Aanya Desai'],
 ['Sunita Kapoor'],
 ['Aarav Shah'],
 ['Isha Rana'],
 ['Dhruv Bansal'],
 ['Kriti Chauhan'],
 ['Ravi Iyer'],
 ['Vikram Roy'],
 ['Deepa Mukherjee'],
 ['Komal Roy'],
 ['Ravi Roy'],
 ['Manish Mishra'],
 ['Dhruv Khanna'],
 ['Ayush Agarwal'],
 ['Ayush Nair'],
 ['Rekha Reddy'],
 ['Aditya Iyer'],
 ['Manish Gupta'],
 ['Priya Saxena'],
 ['Simran Rao'],
 ['Harsh Arora'],
 ['Ritvik Jain'],
 ['Karan Patel'],
 ['Tanvi Roy'],
 ['Rekha Verma'],
 ['Dhruv Sethi'],
 ['Amit Agarwal'],
 ['Divya Arora'],
 ['Shubham Prasad'],
 ['Arjun Joshi'],
 ['Tarun Iyer'],
 ['Aarav Mehta'],
 ['Preeti Srivastava'],
 ['Deepak Roy'],
 ['Tanya Joshi'],
 ['Komal Mehta'],
 ['Tarun Chauhan'],
 ['Tanya Sinha'],
 ['Aditi Malhotra'],
 ['Sameer Jain'],
 ['Preeti Ghosh'],
 ['Meera Jain'],
 ['Rajat Desai'],
 ['Rakesh Nair'],
 ['Palak Menon'],
 ['Yash Reddy'],
 ['Ravi Singh'],
 ['Varun Reddy'],
 ['Sneha Saxena'],
 ['Piyush Srivastava'],
 ['Abhishek Reddy'],
 ['Ravi Desai'],
 ['Kiran Rao'],
 ['Kriti Desai'],
 ['Sonia Reddy'],
 ['Swati Joshi'],
 ['Anjali Ghosh'],
 ['Ravi Mehta'],
 ['Priya Mukherjee'],
 ['Aanya Das'],
 ['Radhika Malhotra'],
 ['Riya Pandey'],
 ['Yash Kumar'],
 ['Neeraj Kumar'],
 ['Arjun Reddy'],
 ['Amit Yadav'],
 ['Simran Singh'],
 ['Gaurav Desai'],
 ['Neeraj Singh'],
 ['Payal Roy'],
 ['Neeraj Rana'],
 ['Anil Verma'],
 ['Aanya Mehta'],
 ['Kabir Mishra'],
 ['Piyush Malhotra'],
 ['Ravi Banerjee'],
 ['Manish Chauhan'],
 ['Kiran Iyer'],
 ['Mohit Pandey'],
 ['Varun Pandey'],
 ['Karan Iyer'],
 ['Saurabh Agarwal'],
 ['Rakesh Mishra'],
 ['Rohan Verma'],
 ['Nisha Mishra'],
 ['Muskan Khanna'],
 ['Aditya Dutta'],
 ['Kriti Chauhan'],
 ['Nandini Srivastava'],
 ['Meera Reddy'],
 ['Ankit Chauhan'],
 ['Yash Kapoor'],
 ['Aanya Patel'],
 ['Simran Joshi'],
 ['Ankit Sethi'],
 ['Rajesh Sharma'],
 ['Nandini Dutta'],
 ['Siddharth Pandey'],
 ['Madan Kapoor'],
 ['Rahul Gupta'],
 ['Juhi Yadav'],
 ['Radhika Nair'],
 ['Shubham Khanna'],
 ['Akash Arora'],
 ['Sneha Khanna'],
 ['Radhika Khanna'],
 ['Deepa Yadav'],
 ['Kavya Bansal'],
 ['Aanya Reddy'],
 ['Yash Arora'],
 ['Tarun Patel'],
 ['Anil Tiwari'],
 ['Tanya Chopra'],
 ['Sunita Reddy'],
 ['Rekha Mehta'],
 ['Preeti Mishra'],
 ['Sakshi Srivastava'],
 ['Rakesh Sharma'],
 ['Manish Chauhan'],
 ['Sameer Iyer'],
 ['Rakesh Srivastava'],
 ['Ayush Sethi'],
 ['Swati Khanna'],
 ['Komal Roy'],
 ['Aditi Desai'],
 ['Ravi Chopra'],
 ['Neeraj Saxena'],
 ['Tanya Singh'],
 ['Kavya Dutta'],
 ['Abhishek Gupta'],
 ['Nikhil Dutta'],
 ['Ritvik Singh'],
 ['Rahul Ghosh'],
 ['Arjun Kapoor'],
 ['Isha Prasad'],
 ['Tanya Tiwari'],
 ['Arjun Nair'],
 ['Pooja Banerjee'],
 ['Sameer Desai'],
 ['Tarun Mishra'],
 ['Payal Jain'],
 ['Ishaan Agarwal'],
 ['Siddharth Saxena'],
 ['Tarun Verma'],
 ['Ravi Iyer'],
 ['Neeraj Desai'],
 ['Dhruv Nair'],
 ['Mohit Das'],
 ['Divya Sinha'],
 ['Kabir Mehta'],
 ['Shreya Rao'],
 ['Meera Desai'],
 ['Sameer Menon'],
 ['Radhika Yadav'],
 ['Amit Mukherjee'],
 ['Madan Patel'],
 ['Nisha Patel'],
 ['Pranav Saxena'],
 ['Pranav Bansal'],
 ['Ankit Khanna'],
 ['Mohit Nair'],
 ['Rahul Yadav'],
 ['Sameer Saxena'],
 ['Rekha Verma'],
 ['Preeti Sinha'],
 ['Payal Mishra'],
 ['Tanya Khanna'],
 ['Nandini Agarwal'],
 ['Dev Srivastava'],
 ['Bhavna Sinha'],
 ['Aanya Mehta'],
 ['Aditya Rao'],
 ['Ishaan Sharma'],
 ['Vivaan Khanna'],
 ['Manish Roy'],
 ['Rahul Chauhan'],
 ['Pranav Kumar'],
 ['Ritvik Sethi'],
 ['Deepa Malhotra'],
 ['Aanya Roy'],
 ['Amit Saxena'],
 ['Arjun Banerjee'],
 ['Harsh Banerjee'],
 ['Kiran Prasad'],
 ['Rajat Chopra'],
 ['Riya Agarwal'],
 ['Shreya Iyer'],
 ['Kabir Kumar'],
 ['Anjali Jain'],
 ['Muskan Rao'],
 ['Varun Arora'],
 ['Mohit Rana'],
 ['Akash Prasad'],
 ['Meera Yadav'],
 ['Priya Rana'],
 ['Dev Gupta'],
 ['Preeti Sethi'],
 ['Juhi Shah'],
 ['Shruti Verma'],
 ['Abhishek Srivastava'],
 ['Aditi Khanna'],
 ['Mohit Saxena'],
 ['Varun Ghosh'],
 ['Mansi Rana'],
 ['Ishaan Verma'],
 ['Divya Pandey'],
 ['Swati Verma'],
 ['Nandini Sethi'],
 ['Deepak Yadav'],
 ['Kiran Sinha'],
 ['Rekha Khanna'],
 ['Komal Ghosh'],
 ['Dhruv Prasad'],
 ['Divya Agarwal'],
 ['Gaurav Kapoor'],
 ['Ishaan Dutta'],
 ['Mohit Jain'],
 ['Yash Mishra'],
 ['Mansi Patel'],
 ['Meera Rana'],
 ['Payal Dutta'],
 ['Rajesh Patel'],
 ['Pooja Rao'],
 ['Divya Ghosh'],
 ['Pranav Singh'],
 ['Deepak Banerjee'],
 ['Deepak Sethi'],
 ['Naveen Khanna'],
 ['Amit Tiwari'],
 ['Aman Shah'],
 ['Shubham Mishra'],
 ['Gaurav Sinha'],
 ['Mansi Singh'],
 ['Komal Gupta'],
 ['Shreya Saxena'],
 ['Shreya Shah'],
 ['Dev Yadav'],
 ['Manish Arora'],
 ['Isha Shah'],
 ['Palak Jain'],
 ['Preeti Sethi'],
 ['Muskan Joshi'],
 ['Dev Roy'],
 ['Ishaan Chauhan'],
 ['Mansi Gupta'],
 ['Sakshi Reddy'],
 ['Mohit Ghosh'],
 ['Vivaan Mukherjee'],
 ['Sneha Arora'],
 ['Ritvik Saxena'],
 ['Ishaan Joshi'],
 ['Yash Bansal'],
 ['Aditi Rao'],
 ['Isha Srivastava'],
 ['Ishaan Banerjee'],
 ['Priya Dutta'],
 ['Ankit Saxena'],
 ['Ananya Banerjee'],
 ['Mansi Singh'],
 ['Mansi Prasad'],
 ['Tanvi Reddy'],
 ['Simran Kapoor'],
 ['Arjun Yadav'],
 ['Nikhil Sethi'],
 ['Sakshi Ghosh'],
 ['Nisha Desai'],
 ['Preeti Jain'],
 ['Varun Desai'],
 ['Dev Desai'],
 ['Sonia Dutta'],
 ['Preeti Prasad'],
 ['Ravi Srivastava'],
 ['Aarav Banerjee'],
 ['Nandini Chopra'],
 ['Aanya Mishra'],
 ['Mohit Chopra'],
 ['Harsh Shah'],
 ['Madan Dutta'],
 ['Mansi Banerjee'],
 ['Rakesh Arora'],
 ['Nikhil Kumar'],
 ['Anjali Chopra'],
 ['Karan Sethi'],
 ['Divya Tiwari'],
 ['Akash Malhotra'],
 ['Shruti Verma'],
 ['Ayush Mehta'],
 ['Kavya Patel'],
 ['Aditya Jain'],
 ['Shreya Banerjee'],
 ['Varun Rana'],
 ['Sneha Pandey'],
 ['Rakesh Jain'],
 ['Anil Rana'],
 ['Aman Malhotra'],
 ['Kavya Roy'],
 ['Bhavna Ghosh'],
 ['Anjali Agarwal'],
 ['Sameer Sinha'],
 ['Vivaan Joshi'],
 ['Isha Kumar'],
 ['Ravi Rao'],
 ['Amit Arora'],
 ['Mansi Sethi'],
 ['Shubham Reddy'],
 ['Preeti Malhotra'],
 ['Tarun Verma'],
 ['Payal Menon'],
 ['Aditya Malhotra'],
 ['Radhika Banerjee'],
 ['Nikhil Chauhan'],
 ['Vikram Kapoor'],
 ['Kavya Shah'],
 ['Juhi Bansal'],
 ['Meera Pandey'],
 ['Neeraj Prasad'],
 ['Aditi Singh'],
 ['Rajesh Rana'],
 ['Gaurav Das'],
 ['Sunita Shah'],
 ['Aman Das'],
 ['Sonia Patel'],
 ['Gaurav Mehta'],
 ['Harsh Kapoor'],
 ['Nandini Kumar'],
 ['Meera Joshi'],
 ['Divya Tiwari'],
 ['Ravi Bansal'],
 ['Pranav Prasad'],
 ['Muskan Khanna'],
 ['Madan Malhotra'],
 ['Neha Rana'],
 ['Isha Mehta'],
 ['Nisha Desai'],
 ['Pranav Chopra'],
 ['Rakesh Shah'],
 ['Neha Singh'],
 ['Neha Nair'],
 ['Anjali Mishra'],
 ['Rajesh Mukherjee'],
 ['Shreya Dutta'],
 ['Sneha Khanna'],
 ['Nisha Dutta'],
 ['Vivek Ghosh'],
 ['Ankit Mukherjee'],
 ['Amit Kapoor'],
 ['Radhika Jain'],
 ['Ananya Tiwari'],
 ['Muskan Verma'],
 ['Aarav Ghosh'],
 ['Harsh Ghosh'],
 ['Dev Jain'],
 ['Kabir Tiwari'],
 ['Priya Reddy'],
 ['Naveen Prasad'],
 ['Saurabh Rana'],
 ['Sameer Sharma'],
 ['Ravi Iyer'],
 ['Akash Ghosh'],
 ['Arjun Srivastava'],
 ['Meera Saxena'],
 ['Piyush Agarwal'],
 ['Ravi Mishra'],
 ['Manish Dutta'],
 ['Tanvi Singh'],
 ['Manish Yadav'],
 ['Riya Pandey'],
 ['Yash Menon'],
 ['Pranav Singh'],
 ['Madan Saxena'],
 ['Dhruv Joshi'],
 ['Ritvik Kapoor'],
 ['Dhruv Chopra'],
 ['Saurabh Yadav'],
 ['Juhi Gupta'],
 ['Shruti Agarwal'],
 ['Shubham Ghosh'],
 ['Madan Sethi'],
 ['Rahul Saxena'],
 ['Swati Sethi'],
 ['Anil Khanna'],
 ['Sonia Ghosh'],
 ['Preeti Kapoor'],
 ['Shruti Iyer'],
 ['Sameer Tiwari'],
 ['Arjun Shah'],
 ['Pranav Chauhan'],
 ['Anjali Bansal'],
 ['Rakesh Shah'],
 ['Madan Agarwal'],
 ['Bhavna Arora'],
 ['Rakesh Sinha'],
 ['Anjali Shah'],
 ['Yash Rao'],
 ['Ayush Bansal'],
 ['Ishaan Banerjee'],
 ['Gaurav Menon'],
 ['Aarav Kumar'],
 ['Sneha Mehta'],
 ['Rajesh Tiwari'],
 ['Aditya Verma'],
 ['Isha Pandey'],
 ['Swati Singh'],
 ['Vikram Kumar'],
 ['Mohit Patel'],
 ['Simran Chopra'],
 ['Divya Roy'],
 ['Shreya Verma'],
 ['Shruti Khanna'],
 ['Deepa Joshi'],
 ['Mansi Jain'],
 ['Aditya Srivastava'],
 ['Neeraj Arora'],
 ['Aanya Jain'],
 ['Divya Dutta'],
 ['Vikram Sethi'],
 ['Aditya Yadav'],
 ['Siddharth Sethi'],
 ['Tanvi Kapoor'],
 ['Bhavna Banerjee'],
 ['Meera Roy'],
 ['Neeraj Bansal'],
 ['Ananya Shah'],
 ['Rekha Sharma'],
 ['Payal Das'],
 ['Amit Menon'],
 ['Ankit Prasad'],
 ['Sneha Desai'],
 ['Bhavna Agarwal'],
 ['Vikram Shah'],
 ['Swati Sharma'],
 ['Palak Rao'],
 ['Vikram Dutta'],
 ['Nisha Shah'],
 ['Aman Mukherjee'],
 ['Ravi Desai'],
 ['Rekha Rana'],
 ['Madan Khanna'],
 ['Rekha Dutta'],
 ['Siddharth Sethi'],
 ['Karan Jain'],
 ['Shruti Banerjee'],
 ['Ritvik Verma'],
 ['Payal Roy'],
 ['Anil Arora'],
 ['Muskan Chauhan'],
 ['Mansi Banerjee'],
 ['Aman Sethi'],
 ['Shruti Desai'],
 ['Sameer Menon'],
 ['Shreya Reddy'],
 ['Neeraj Singh'],
 ['Aanya Sharma'],
 ['Ravi Singh'],
 ['Saurabh Pandey'],
 ['Dev Mukherjee'],
 ['Aarav Joshi'],
 ['Komal Tiwari'],
 ['Aditya Jain'],
 ['Saurabh Gupta'],
 ['Ritvik Malhotra'],
 ['Kabir Prasad'],
 ['Pooja Gupta'],
 ['Dev Khanna'],
 ['Rahul Gupta'],
 ['Rekha Shah'],
 ['Sonia Chopra'],
 ['Aanya Shah'],
 ['Arjun Dutta'],
 ['Kiran Yadav'],
 ['Kriti Sharma'],
 ['Nikhil Menon'],
 ['Aarav Sethi'],
 ['Vivaan Malhotra'],
 ['Siddharth Bansal'],
 ['Mohit Nair'],
 ['Palak Malhotra'],
 ['Nandini Pandey'],
 ['Ayush Malhotra'],
 ['Ritvik Reddy'],
 ['Sunita Rana'],
 ['Neeraj Sharma'],
 ['Anil Nair'],
 ['Mohit Mishra'],
 ['Vikram Patel'],
 ['Arjun Yadav'],
 ['Deepa Arora'],
 ['Nikhil Reddy'],
 ['Muskan Pandey'],
 ['Deepa Ghosh'],
 ['Abhishek Ghosh'],
 ['Vikram Yadav'],
 ['Manish Reddy'],
 ['Vivaan Dutta'],
 ['Amit Reddy'],
 ['Palak Menon'],
 ['Piyush Ghosh'],
 ['Rahul Saxena'],
 ['Kavya Shah'],
 ['Vikram Desai'],
 ['Muskan Chauhan'],
 ['Nisha Saxena'],
 ['Juhi Prasad'],
 ['Rajesh Prasad'],
 ['Sonia Yadav'],
 ['Amit Singh'],
 ['Nandini Sethi'],
 ['Piyush Desai'],
 ['Piyush Malhotra'],
 ['Pooja Nair'],
 ['Shreya Banerjee'],
 ['Harsh Saxena'],
 ['Shubham Sethi'],
 ['Dhruv Prasad'],
 ['Mansi Das'],
 ['Tarun Agarwal'],
 ['Pooja Kumar'],
 ['Anil Menon'],
 ['Ananya Sethi'],
 ['Aanya Mukherjee'],
 ['Deepak Mukherjee'],
 ['Sakshi Saxena'],
 ['Siddharth Desai'],
 ['Ayush Mishra'],
 ['Deepa Tiwari'],
 ['Riya Verma'],
 ['Ankit Pandey'],
 ['Abhishek Sinha'],
 ['Yash Iyer'],
 ['Gaurav Verma'],
 ['Harsh Sinha'],
 ['Piyush Pandey'],
 ['Aman Mukherjee'],
 ['Abhishek Sharma'],
 ['Rajat Khanna'],
 ['Kabir Dutta'],
 ['Arjun Malhotra'],
 ['Anil Malhotra'],
 ['Muskan Menon'],
 ['Divya Kapoor'],
 ['Meera Chauhan'],
 ['Divya Agarwal'],
 ['Vivek Bansal'],
 ['Divya Kumar'],
 ['Anjali Shah'],
 ['Piyush Arora'],
 ['Riya Jain'],
 ['Divya Chauhan'],
 ['Tanya Shah'],
 ['Nikhil Malhotra'],
 ['Sameer Joshi'],
 ['Aditi Sethi'],
 ['Radhika Jain'],
 ['Sunita Tiwari'],
 ['Kabir Shah'],
 ['Anjali Bansal'],
 ['Rahul Reddy'],
 ['Nisha Pandey'],
 ['Kiran Mishra'],
 ['Nandini Mukherjee'],
 ['Ankit Sinha'],
 ['Dev Yadav'],
 ['Aditya Iyer'],
 ['Sonia Singh'],
 ['Mohit Kumar'],
 ['Sonia Mukherjee'],
 ['Sakshi Shah'],
 ['Ishaan Das'],
 ['Shreya Menon'],
 ['Rohan Patel'],
 ['Rakesh Ghosh'],
 ['Rohan Saxena'],
 ['Madan Bansal'],
 ['Nikhil Arora'],
 ['Aman Patel'],
 ['Nikhil Rana'],
 ['Neha Ghosh'],
 ['Vivaan Pandey'],
 ['Ankit Bansal'],
 ['Karan Menon'],
 ['Swati Roy'],
 ['Pooja Dutta'],
 ['Deepak Sinha'],
 ['Ravi Verma'],
 ['Rekha Rao'],
 ['Ishaan Pandey'],
 ['Sameer Rana'],
 ['Vivaan Ghosh'],
 ['Vivek Iyer'],
 ['Kriti Mukherjee'],
 ['Tarun Mukherjee'],
 ['Rahul Sharma'],
 ['Ravi Banerjee'],
 ['Dhruv Roy'],
 ['Shubham Desai'],
 ['Siddharth Shah'],
 ['Abhishek Bansal'],
 ['Rajat Mehta'],
 ['Nikhil Desai'],
 ['Arjun Reddy'],
 ['Rekha Bansal'],
 ['Naveen Chauhan'],
 ['Aman Saxena'],
 ['Siddharth Agarwal'],
 ['Swati Chopra'],
 ['Pranav Agarwal'],
 ['Divya Kapoor'],
 ['Arjun Jain'],
 ['Komal Shah'],
 ['Ayush Saxena'],
 ['Aarav Tiwari'],
 ['Siddharth Rana'],
 ['Swati Chopra'],
 ['Saurabh Banerjee'],
 ['Neha Mishra'],
 ['Tanvi Shah'],
 ['Sakshi Iyer'],
 ['Abhishek Rao'],
 ['Ananya Nair'],
 ['Vivaan Roy'],
 ['Rohan Arora'],
 ['Payal Desai'],
 ['Deepa Reddy'],
 ['Shubham Prasad'],
 ['Aditi Khanna'],
 ['Rekha Arora'],
 ['Dev Desai'],
 ['Ankit Rana'],
 ['Yash Malhotra'],
 ['Manish Pandey'],
 ['Rajat Saxena'],
 ['Harsh Rana'],
 ['Shubham Banerjee'],
 ['Radhika Srivastava'],
 ['Tarun Menon'],
 ['Mohit Menon'],
 ['Harsh Pandey'],
 ['Ayush Srivastava'],
 ['Sonia Nair'],
 ['Riya Kapoor'],
 ['Shubham Mishra'],
 ['Tarun Yadav'],
 ['Yash Malhotra'],
 ['Akash Khanna'],
 ['Karan Iyer'],
 ['Ananya Chauhan'],
 ['Pranav Roy'],
 ['Saurabh Mishra'],
 ['Juhi Roy'],
 ['Komal Ghosh'],
 ['Juhi Dutta'],
 ['Sonia Dutta'],
 ['Priya Joshi'],
 ['Deepak Reddy'],
 ['Ankit Yadav'],
 ['Vikram Sharma'],
 ['Shreya Agarwal'],
 ['Amit Verma'],
 ['Varun Yadav'],
 ['Nandini Khanna'],
 ['Radhika Sethi'],
 ['Simran Prasad'],
 ['Aarav Chopra'],
 ['Ayush Rana'],
 ['Komal Kapoor'],
 ['Sunita Desai'],
 ['Abhishek Pandey'],
 ['Ritvik Reddy'],
 ['Rajesh Shah'],
 ['Mansi Kumar'],
 ['Karan Singh'],
 ['Rahul Chauhan'],
 ['Dhruv Chauhan'],
 ['Priya Shah'],
 ['Divya Chopra'],
 ['Vivek Singh'],
 ['Divya Khanna'],
 ['Neha Reddy'],
 ['Saurabh Arora'],
 ['Bhavna Chauhan'],
 ['Pranav Banerjee'],
 ['Neeraj Arora'],
 ['Anjali Gupta'],
 ['Rahul Prasad'],
 ['Shruti Jain'],
 ['Tarun Das'],
 ['Tanvi Reddy'],
 ['Yash Nair'],
 ['Ananya Rana'],
 ['Ritvik Nair'],
 ['Rohan Sinha'],
 ['Mansi Rao'],
 ['Shruti Mukherjee'],
 ['Komal Saxena'],
 ['Divya Rao'],
 ['Tarun Verma'],
 ['Kavya Pandey'],
 ['Nandini Ghosh'],
 ['Ananya Verma'],
 ['Deepak Verma'],
 ['Sakshi Sharma'],
 ['Aditya Nair'],
 ['Riya Iyer'],
 ['Yash Malhotra'],
 ['Ayush Mishra'],
 ['Sneha Mehta'],
 ['Pooja Kapoor'],
 ['Siddharth Gupta'],
 ['Naveen Yadav'],
 ['Divya Banerjee'],
 ['Varun Menon'],
 ['Neha Khanna'],
 ['Nikhil Chopra'],
 ['Madan Rana'],
 ['Nikhil Mishra'],
 ['Dhruv Sharma'],
 ['Neeraj Chauhan'],
 ['Rekha Nair'],
 ['Pooja Verma'],
 ['Mohit Rana'],
 ['Tanya Roy'],
 ['Pooja Das'],
 ['Arjun Malhotra'],
 ['Vivek Chauhan'],
 ['Amit Sharma'],
 ['Ayush Sethi'],
 ['Varun Saxena'],
 ['Neeraj Rana'],
 ['Simran Nair'],
 ['Rohan Kapoor'],
 ['Rajat Rana'],
 ['Komal Dutta'],
 ['Piyush Saxena'],
 ['Rakesh Sinha'],
 ['Sameer Joshi'],
 ['Arjun Ghosh'],
 ['Aanya Banerjee'],
 ['Neha Patel'],
 ['Aditya Sharma'],
 ['Riya Yadav'],
 ['Rahul Mukherjee'],
 ['Vivaan Yadav'],
 ['Madan Jain'],
 ...]

In [1]:
import sqlite3
import pandas as pd

con = sqlite3.connect("hims.db")

In [2]:
df = pd.read_sql_query("SELECT * FROM patients", con)

In [3]:
df

,patient_id,fullname,dob,age,gender,marital_status,mobile,email,aadhaar,address,...,family_history,has_insurance,insurance_provider,policy_number,insurance_validity,department,preferred_doctor,appointment_date,appointment_time,created_at
0,PAT20260608084220,kunal,30121995,30,male,single,8860065479,kunal.rwd@gmail.com,123456789101,267,...,no,no,,,,cardiology,rakesh,08-06-2026,02:00,2026-06-08 08:42:20
1,PAT20260812134601,raam,1995-12-1,31,male,married,8860065479,kunal.rwd@gmail.com,999999999999,267,...,sigar and bp,yes,aditya birla,9999999999,2026-12-08,physiology,madan,no,no,2026-08-12 13:46:01
2,PAT20260824135034,Hari Prasad,1995-12-30,30,male,single,9999999999,k@gmail.com,123456789101,121,...,no,no,,,,physician,madan,2026-08-10,12:00,2026-08-24 13:50:34
3,PAT202608290001717,Priya Kumar,2014-08-02,12,Female,Single,6019272848,priya.kumar5263@example.com,362759599856,"12, Station Road",...,Diabetes and hypertension,Yes,Bajaj Allianz,POL95553884,2027-07-09,Physiology,MAD001,2026-08-07,15:00,2026-04-13 23:05:12
4,PAT202608290002649,Arjun Dutta,2011-12-21,14,Male,Single,7854077478,arjun.dutta4861@example.com,903932584086,"176, Park Road",...,Diabetes and hypertension,Yes,Niva Bupa,POL50415463,2027-12-28,Ophthalmology,PRI001,2026-09-03,12:00,2026-07-21 17:05:12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
998,PAT202608290996412,Vivaan Yadav,1991-01-02,35,Female,Divorced,7522760826,vivaan.yadav1034@example.com,996455738143,"919, Station Road",...,None,No,,,,Dermatology,PRI001,2026-07-30,10:30,2026-06-25 07:05:12
999,PAT202608290997575,Madan Jain,1946-10-13,79,Male,Single,7598260690,madan.jain4626@example.com,609876452733,"272, Park Road",...,Thyroid disorder,Yes,HDFC ERGO,POL10699241,2028-05-23,Ophthalmology,PRI001,2026-09-12,09:30,2026-03-13 14:05:12
1000,PAT202608290998317,Rajat Agarwal,1947-03-28,79,Male,Widowed,7352024724,rajat.agarwal3071@example.com,359895273178,"808, Station Road",...,Heart disease,Yes,Care Health,POL28665601,2028-05-01,Dermatology,PRI001,2026-12-26,09:30,2026-04-06 23:05:12
1001,PAT202608290999178,Riya Desai,1984-02-06,42,Other,Single,6689842129,riya.desai6258@example.com,850979267333,"717, Main Road",...,Diabetes,Yes,Star Health,POL77063978,2027-05-19,Physiology,MAD001,2026-07-29,18:45,2026-05-21 23:05:12
1002,PAT202608291000459,Nandini Srivastava,1960-01-17,66,Male,Divorced,7987837139,nandini.srivastava200@example.com,382947814728,"144, Station Road",...,Heart disease,Yes,Aditya Birla Health,POL41922068,2027-02-02,Physiology,MAD001,2026-09-25,11:00,2026-03-01 19:05:12

In [4]:
df.columns

Index(['patient_id', 'fullname', 'dob', 'age', 'gender', 'marital_status',
       'mobile', 'email', 'aadhaar', 'address', 'area', 'city', 'state',
       'pincode', 'blood_group', 'emergency_name', 'emergency_number',
       'symptoms', 'symptom_duration', 'current_condition', 'allergies',
       'previous_surgery', 'family_history', 'has_insurance',
       'insurance_provider', 'policy_number', 'insurance_validity',
       'department', 'preferred_doctor', 'appointment_date',
       'appointment_time', 'created_at'],
      dtype='str')

In [6]:
df.describe()

               age
count  1003.000000
mean     44.694915
std      18.926232
min       5.000000
25%      30.000000
50%      44.000000
75%      58.000000
max      80.000000

In [8]:
df['age'].count_values()

AttributeError: 'Series' object has no attribute 'count_values'